/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class IPrestamoGen extends javax.swing.JInternalFrame {

    /**
     * Creates new form IPrestamoGen
     */
    public IPrestamoGen() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbprestamos = new javax.swing.JTable();
        btnsalir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnEntregar = new javax.swing.JButton();
        btnAplazar = new javax.swing.JButton();
        txtbuscar = new javax.swing.JTextField();
        btnbuscar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);

        tbprestamos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tbprestamos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tbprestamos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbprestamosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbprestamos);

        btnsalir.setText("Atras");
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Prestamos Activos");

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnEntregar.setText("Entregar");
        btnEntregar.setEnabled(false);
        btnEntregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntregarActionPerformed(evt);
            }
        });

        btnAplazar.setText("Aplazar");
        btnAplazar.setEnabled(false);
        btnAplazar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAplazarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEntregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnAplazar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnAplazar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnEntregar)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        txtbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtbuscarActionPerformed(evt);
            }
        });

        btnbuscar.setText("buscar");
        btnbuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnbuscar))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(501, 501, 501)
                                .addComponent(btnsalir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 499, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)))
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnbuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(btnsalir)
                .addContainerGap(32, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtbuscarActionPerformed

    }//GEN-LAST:event_txtbuscarActionPerformed

    private void btnAplazarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAplazarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAplazarActionPerformed

    private void btnbuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbuscarActionPerformed
      String idest = txtbuscar.getText();
      buscar(idest);         
    }//GEN-LAST:event_btnbuscarActionPerformed

    private void btnEntregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntregarActionPerformed
      String idest=txtbuscar.getText();
      metodoentregar(idest); 
           
    }//GEN-LAST:event_btnEntregarActionPerformed

    private void tbprestamosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbprestamosMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbprestamosMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAplazar;
    private javax.swing.JButton btnEntregar;
    private javax.swing.JButton btnbuscar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbprestamos;
    private javax.swing.JTextField txtbuscar;
    // End of variables declaration//GEN-END:variables
Conectar cc= new Conectar();
Connection cn = cc.conexion();


void metodoentregar (String idest) {
    String idlibro= JOptionPane.showInputDialog("Confirma con ID del Libro para Entregar");    
     String sql="UPDATE prestamo SET entregado=true WHERE idest='"+idest+"' && idlibro='"+idlibro+"'";   
        try {
            PreparedStatement pst = cn.prepareStatement(sql);
            int m=pst.executeUpdate();
                if(m>0){
                    JOptionPane.showMessageDialog(this, "se entrego libro");
                    buscar(idest);
                }         
        
        } catch (SQLException ex) {
            Logger.getLogger(IPrestamoGen.class.getName()).log(Level.SEVERE, null, ex);
        }
}
void metodoaplazar (String idest){
     Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);
        String DataSystem = " ";
        String idlibro= JOptionPane.showInputDialog("Confirma con ID del Libro que desea aplazar");    
        String sql="SELECT FROM prestamo WHERE idest='"+idest+"' && idlibro='"+idlibro+"'";   
        
         try {
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(sql);  
          while(rs.next()){
             DataSystem=rs.getString("F_Entrega");
            }       
             System.out.println(DataSystem);
           //  fecha.add(DataSystem);
         
         } catch (SQLException ex) {
            Logger.getLogger(IPrestamoGen.class.getName()).log(Level.SEVERE, null, ex);
        }
        
}
void buscar (String bus){
    Boolean Desvio = false;
      DefaultTableModel tabla= new DefaultTableModel();
      String buscar=bus;
      String consulta="";
        if (txtbuscar.getText().equals("")) {           
            consulta = "SELECT p.id,p.idest,idrec,l.titulo, p.F_inicio,p.F_Entrega,l.id FROM prestamo p INNER JOIN Libros l ON p.idlibro = l.id WHERE p.entregado=false";
            btnEntregar.setEnabled(false); 
            Desvio = false;
        }
        else {
          consulta = "SELECT p.id,p.idest,idrec,l.titulo, p.F_inicio,p.F_Entrega,l.id FROM prestamo p INNER JOIN Libros l ON p.idlibro = l.id WHERE p.idest='"+buscar+"' && p.entregado=false";
            btnEntregar.setEnabled(false);  
            Desvio = true;
        }
        
        String []titulos={"ID","Ncontrol","RC","Libro","Fecha_Inicio","Fecha_Entrega"};
        tabla.setColumnIdentifiers(titulos);
        this.tbprestamos.setModel(tabla);
        String []Datos= new String [6];
        Datos[0]="";
        try {
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(consulta);  
         while(rs.next()){
                    Datos[0]=rs.getString("p.id");
                    Datos[1]=rs.getString("p.idest");
                    Datos[2]=rs.getString("p.idrec");
                    Datos[3]=rs.getString("l.titulo");
                    Datos[4]=rs.getString("p.F_inicio");
                    Datos[5]=rs.getString("p.F_entrega");
                    tabla.addRow(Datos);
            }       
         if (Datos[0].equals("")){Desvio=false;}
         
            if(Desvio==false){
                btnEntregar.setEnabled(false);
                btnAplazar.setEnabled(false);
            }
            else {btnEntregar.setEnabled(true);
                  btnAplazar.setEnabled(false);
            }
        }
        catch (SQLException ex) {
            Logger.getLogger(IPrestamoGen.class.getName()).log(Level.SEVERE, null, ex);
        }
}
}
