/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import static Frame.Estudiantes.lblcontrol;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author erick
 */
public class Iprestamoact extends javax.swing.JInternalFrame {

    /**
     * Creates new form Iregistrop
     */
    public Iprestamoact() {
       
        initComponents();
         buscarprestamo();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbpresact = new javax.swing.JTable();
        btnatras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtStatus = new javax.swing.JLabel();

        setClosable(true);

        tbpresact.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tbpresact);

        btnatras.setText("Atras");
        btnatras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnatrasActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Prestamo Activo");

        txtStatus.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtStatus.setText("asd");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(txtStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(txtStatus)
                .addGap(21, 21, 21)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                .addGap(26, 26, 26)
                .addComponent(btnatras, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnatrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnatrasActionPerformed
    this.dispose();;
    }//GEN-LAST:event_btnatrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnatras;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbpresact;
    private javax.swing.JLabel txtStatus;
    // End of variables declaration//GEN-END:variables
Conectar cc= new Conectar();
Connection cn = cc.conexion();

void buscarprestamo(){
    
    DefaultTableModel tabla= new DefaultTableModel();
    String idest=lblcontrol.getText();
    String consulta = " ";
    consulta = "SELECT p.id,p.idest,idrec,l.titulo, p.F_inicio,p.F_Entrega,l.id FROM prestamo p INNER JOIN Libros l ON p.idlibro = l.id WHERE p.idest='"+idest+"' && p.entregado=false";
    String []titulos={"ID","Ncontrol","RC","Libro","Fecha_Inicio","Fecha_Entrega"};
        tabla.setColumnIdentifiers(titulos);
        this.tbpresact.setModel(tabla);
        String []Datos= new String [6];
        Datos[0]="";
        try {
         Statement st = cn.createStatement();
         ResultSet rs = st.executeQuery(consulta);  
         while(rs.next()){
                    Datos[0]=rs.getString("p.id");
                    Datos[1]=rs.getString("p.idest");
                    Datos[2]=rs.getString("p.idrec");
                    Datos[3]=rs.getString("l.titulo");
                    Datos[4]=rs.getString("p.F_inicio");
                    Datos[5]=rs.getString("p.F_entrega");
                    tabla.addRow(Datos);
            }
        if(Datos[0].equals("")){
        txtStatus.setText("Usted es Acreedor de un Prestamo");
        }
        else {
          txtStatus.setText("Usted debe entregar los siguientes libros en los proximos dias..");
        }
            
        
        
        
        }
catch (SQLException ex) {
            Logger.getLogger(IPrestamoGen.class.getName()).log(Level.SEVERE, null, ex);
        }

}
}
