/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author erick
 */
public class IRegistrarP extends javax.swing.JInternalFrame {
    
    public String Finicial;
    public String Fentrega;
    public String idlibro;
      /*
     * Creates new form IRegistrarP
     */
    public IRegistrarP() {
        initComponents();
          calendario();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtncontrol = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        btnregistrar = new javax.swing.JButton();
        btncancelar = new javax.swing.JButton();
        ptnombre = new javax.swing.JLabel();
        btnverificar1 = new javax.swing.JButton();
        txtlibro = new javax.swing.JTextField();
        btnverificar2 = new javax.swing.JButton();
        ptlibro = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        dateini = new javax.swing.JLabel();
        dateen = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("NControl");

        txtncontrol.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtncontrol.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtncontrolMouseClicked(evt);
            }
        });
        txtncontrol.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtncontrolActionPerformed(evt);
            }
        });

        jLabel2.setText("IDLibro");

        btnregistrar.setText("Registrar");
        btnregistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnregistrarActionPerformed(evt);
            }
        });

        btncancelar.setText("Cancelar");
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        ptnombre.setText("    ");

        btnverificar1.setText("Verificar");
        btnverificar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificar1ActionPerformed(evt);
            }
        });

        txtlibro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtlibroMouseClicked(evt);
            }
        });
        txtlibro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtlibroActionPerformed(evt);
            }
        });

        btnverificar2.setText("Verificar");
        btnverificar2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnverificar2ActionPerformed(evt);
            }
        });

        ptlibro.setAlignmentX(1.0F);
        ptlibro.setAlignmentY(1.0F);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        dateini.setText("fechadehoy");

        dateen.setText("fechadeentrega");

        jLabel3.setText("Fecha Inicio:");

        jLabel4.setText("Fecha Entrega:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateini)
                    .addComponent(dateen))
                .addGap(158, 158, 158))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(dateini, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateen)
                    .addComponent(jLabel4))
                .addContainerGap(27, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(94, 94, 94)
                        .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(txtncontrol, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnverificar1))
                            .addComponent(ptnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ptlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(4, 4, 4)
                                .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(39, 39, 39)
                                .addComponent(btnverificar2))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtncontrol, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnverificar1))))
                .addGap(6, 6, 6)
                .addComponent(ptnombre, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtlibro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnverificar2))))
                .addGap(6, 6, 6)
                .addComponent(ptlibro, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnregistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtncontrolActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtncontrolActionPerformed
            
       
    }//GEN-LAST:event_txtncontrolActionPerformed

    private void btnregistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnregistrarActionPerformed
String idest,idrec,Fini,Fent,dlibro;
    Fini=Finicial;
    Fent=Fentrega;
            String sql="";
            if (!btnverificar1.isEnabled()&& !btnverificar2.isEnabled()){
            dlibro=idlibro;
            idest=txtncontrol.getText();
            idrec=Login.txtid.getText();
            sql="INSERT INTO prestamo (idest,idrec,idlibro,F_inicio,F_Entrega) VALUES (?,?,?,?,?)";
        try {
            PreparedStatement pst  = cn.prepareStatement(sql);
            pst.setString(1, idest);
            pst.setString(2, idrec);
            pst.setString(3, dlibro);
            pst.setString(4, Fini);
            pst.setString(5, Fent);
            int n=pst.executeUpdate();
            if(n>0){
            JOptionPane.showMessageDialog(null, "Registro Guardado con Exito");
            limpiar();
            }      
        } catch (SQLException ex) {
            Logger.getLogger(IRegistrarP.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(null, "hubo un error en el registro");
            
        }
            }
            else{
            JOptionPane.showMessageDialog(null, "Verifique los campos");
            }
    }//GEN-LAST:event_btnregistrarActionPerformed

    private void btnverificar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificar1ActionPerformed
    String id = txtncontrol.getText();
    verificar1(id);
           
    }//GEN-LAST:event_btnverificar1ActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btncancelarActionPerformed

    private void txtlibroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtlibroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtlibroActionPerformed

    private void btnverificar2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnverificar2ActionPerformed
    String not =txtlibro.getText();
    verificarl(not);
        
    }//GEN-LAST:event_btnverificar2ActionPerformed

    private void txtncontrolMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtncontrolMouseClicked
            btnverificar1.setEnabled(true);
    }//GEN-LAST:event_txtncontrolMouseClicked

    private void txtlibroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtlibroMouseClicked
           btnverificar2.setEnabled(true);
    }//GEN-LAST:event_txtlibroMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnregistrar;
    private javax.swing.JButton btnverificar1;
    private javax.swing.JButton btnverificar2;
    private javax.swing.JLabel dateen;
    private javax.swing.JLabel dateini;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel ptlibro;
    private javax.swing.JLabel ptnombre;
    private javax.swing.JTextField txtlibro;
    private javax.swing.JTextField txtncontrol;
    // End of variables declaration//GEN-END:variables
Conectar cc = new Conectar();
Connection cn = cc.conexion();

void verificar1 (String id){
   String Nombre ="",idest="";
    String sql="Select * from estudiantes where id='"+id+"'";
            Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
        while(rs.next())
            {
             Nombre=rs.getString("Nombre");
            // turno=rs.getString("Turno");
            }
         if (Nombre.equals("")){
             JOptionPane.showMessageDialog(null, "No se encontro Resultado");
         }
         else {
             ptnombre.setText(Nombre);
             btnverificar1.setEnabled(false);
         
         }
        
        } catch (SQLException ex) {
            Logger.getLogger(IRegistrarP.class.getName()).log(Level.SEVERE, null, ex);
        }
}
void verificarl (String id){
   String titulo="",turno="";
    String sql="Select * from libros where id='"+id+"' || titulo='"+id+"'";
            Statement st;
        try {
            st = cn.createStatement();
            ResultSet rs = st.executeQuery(sql);
        while(rs.next())
            {
             titulo=rs.getString("titulo");
          //   turno=rs.getString("Turno");
            }
         if (titulo.equals("")){
             JOptionPane.showMessageDialog(null, "No se encontro Resultado");
         }
         else {
             idlibro=id;
             ptlibro.setText(titulo);
             btnverificar2.setEnabled(false);
         }
        
        } catch (SQLException ex) {
            Logger.getLogger(IRegistrarP.class.getName()).log(Level.SEVERE, null, ex);
        }
}
void calendario () {
    Calendar fecha = new GregorianCalendar();
        int año = fecha.get(Calendar.YEAR);
        int mes = fecha.get(Calendar.MONTH);
        int dia = fecha.get(Calendar.DAY_OF_MONTH);
        int hora = fecha.get(Calendar.HOUR_OF_DAY);
        int minuto = fecha.get(Calendar.MINUTE);
        int segundo = fecha.get(Calendar.SECOND);

        dateini.setText(dia + "/" + (mes+1) + "/" + año+"   "+hora+":"+minuto+"hrs");
        Finicial = (año+"-"+(mes+1)+"-"+dia);
        fecha.add(Calendar.DAY_OF_MONTH,5);
        año = fecha.get(Calendar.YEAR);
        mes = fecha.get(Calendar.MONTH);
        dia = fecha.get(Calendar.DAY_OF_MONTH);
       dateen.setText(dia + "/" + (mes+1) + "/" + año);
       Fentrega = (año+"-"+(mes+1)+"-"+dia);
              }

void limpiar (){    
    txtncontrol.setText("");
    txtlibro.setText("");
}
}

