/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frame;

import java.awt.Image;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.DesktopManager;

/**
 *
 * @author erick
 */
public class Recepcionista extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Recepcionista() {
        this.setLocation(200, 50);
        initComponents();
        J1.setIcon(setIcono("/imagenes/123.png",J1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        J1 = new javax.swing.JLabel();
        lblnombre = new javax.swing.JLabel();
        lblturno = new javax.swing.JLabel();
        btnrp = new javax.swing.JButton();
        btnact = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnbibli = new javax.swing.JButton();
        jdpescritorio = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        J1.setText("   ");
        J1.setToolTipText("");
        getContentPane().add(J1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 80, 80));

        lblnombre.setText("TNombre");
        getContentPane().add(lblnombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        lblturno.setText("TTurno");
        getContentPane().add(lblturno, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        btnrp.setText("Registrar Prestamo");
        btnrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnrpActionPerformed(evt);
            }
        });
        getContentPane().add(btnrp, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 20, 160, 50));

        btnact.setText("Prestamos Activos");
        btnact.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnactActionPerformed(evt);
            }
        });
        getContentPane().add(btnact, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 20, 160, 50));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setText("RECEPCIONISTA");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, -1, -1));

        btnbibli.setText("Biblioteca");
        btnbibli.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbibliActionPerformed(evt);
            }
        });
        getContentPane().add(btnbibli, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 20, 160, 50));
        getContentPane().add(jdpescritorio, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 80, 820, 480));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/salida.png"))); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, 50, 40));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnbibliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbibliActionPerformed
          IBiblioteca cli = new IBiblioteca();
                 jdpescritorio.add(cli);
                     cli.show();;  
              
    }//GEN-LAST:event_btnbibliActionPerformed

    private void btnrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnrpActionPerformed
                IRegistrarP cli = new IRegistrarP();
                 jdpescritorio.add(cli);
                     cli.show();;  
                    }//GEN-LAST:event_btnrpActionPerformed

    private void btnactActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnactActionPerformed
                IPrestamoGen cli = new IPrestamoGen();
                jdpescritorio.add(cli);
                cli.show();
    }//GEN-LAST:event_btnactActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
                this.setVisible(false);
                JOptionPane.showMessageDialog(null," ADIOS ");
                Login ingreso = new Login();
                ingreso.setVisible(true);
                ingreso.pack();  
               
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Recepcionista.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Recepcionista().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel J1;
    private javax.swing.JButton btnact;
    private javax.swing.JButton btnbibli;
    private javax.swing.JButton btnrp;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JDesktopPane jdpescritorio;
    public static javax.swing.JLabel lblnombre;
    public static javax.swing.JLabel lblturno;
    // End of variables declaration//GEN-END:variables

    public Icon setIcono (String url, JLabel panel){
        ImageIcon icon = new ImageIcon (getClass().getResource(url));
        int ancho = panel.getWidth();
        int alto = panel.getHeight();
        ImageIcon icono = new ImageIcon(icon.getImage().getScaledInstance(ancho,alto, Image.SCALE_DEFAULT));
        return icono;
    }
}
